version: 2
jobs:
  build:
    docker:
      - image: quay.io/pypa/manylinux1_x86_64
    steps:
        - checkout
        - run: yum -y install zlib-devel
        - run:
            shell: /bin/bash
            command: ./configure && make CFLAGS="-static" EXEEXT="-static"
        - run: strip rsync-static
        - store_artifacts:
            path: rsync-static
